# Modelling

In [3]:
# Importing required dependancies 
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import math
import time
import bisect

Importing some of the previous information in Data Understanding & Preperation

In [17]:
newdf = pd.read_csv('binned_data_24hrs.csv')
newdf.drop('date').T.iloc[::-1]

,0,1,2,3,4,5,6,7,8,9,...,2851,2852,2853,2854,2855,2856,2857,2858,2859,2860
1999,1.027417e+00,1.000000e-03,3.000000e-03,3.000000e-03,1.028907e-02,1.037706e+00,1.027417e+00,0.000000e+00,1.000000e-03,1.000000e+00,...,1.000000e-03,4.612000e+01,1.000000e+00,2.856009e-02,1.000000e-03,1.050000e+00,1.050000e+00,5.000000e-02,2.000000e-03,0.000000e+00
1998,1.028907e-02,0.000000e+00,3.020000e-01,3.020000e-01,3.000000e-03,3.000000e-03,1.028907e-02,1.037706e+00,0.000000e+00,3.000000e-03,...,4.840270e-03,1.000000e+00,1.000000e-03,1.729110e-01,1.084027e-02,6.317490e-01,0.000000e+00,1.000000e+00,1.000000e-03,1.000000e-03
1997,3.000000e-03,1.471872e+01,1.544140e+00,1.544140e+00,3.020000e-01,3.020000e-01,3.000000e-03,3.000000e-03,5.000000e-02,0.000000e+00,...,6.000000e-03,0.000000e+00,2.000000e-03,0.000000e+00,5.000000e-02,7.956009e-02,7.113091e-01,6.827490e-01,9.840270e-03,2.000000e-03
1996,3.020000e-01,3.433497e-02,1.492611e-02,1.492611e-02,1.544140e+00,1.544140e+00,3.020000e-01,3.020000e-01,0.000000e+00,2.000000e-03,...,1.050000e+00,2.000000e-03,4.840270e-03,4.664211e-02,1.000000e+00,1.729110e-01,1.729110e-01,2.856009e-02,5.100000e-02,4.840270e-03
1995,1.544140e+00,3.554217e+00,1.960000e+00,1.960000e+00,1.492611e-02,1.492611e-02,1.544140e+00,1.544140e+00,3.105029e-01,3.200000e-03,...,6.317490e-01,1.000000e-03,6.000000e-03,1.302200e+00,6.317490e-01,0.000000e+00,0.000000e+00,1.729110e-01,1.000000e+00,6.000000e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,3.000000e-01,1.210539e+01,5.500000e-02,0.000000e+00,6.078463e-02,5.784630e-03,3.000000e-01,3.000000e-01,0.000000e+00,1.004039e+01,...,6.775292e-01,1.000000e-01,6.000000e-01,4.713970e+00,5.000000e-03,1.010000e-01,1.000000e-01,1.000000e-01,6.775292e-01,6.000000e-01
2,6.078463e-02,3.154774e-02,8.564267e-02,8.564267e-02,8.564267e-02,5.500000e-02,6.078463e-02,6.078463e-02,1.469388e+00,8.963930e-01,...,5.000000e-03,1.230000e-01,6.775292e-01,3.533500e-01,0.000000e+00,1.130000e-02,1.000000e-03,1.000000e-03,5.000000e-03,6.775292e-01
1,8.564267e-02,4.117904e-01,1.500000e-01,1.500000e-01,1.500000e-01,8.564267e-02,8.564267e-02,8.564267e-02,0.000000e+00,2.950634e-01,...,1.000000e-01,6.000000e-01,5.000000e-03,1.166026e+00,1.000000e-01,4.713970e+00,4.725270e+00,1.130000e-02,0.000000e+00,5.000000e-03
0,1.500000e-01,0.000000e+00,1.052499e+00,1.052499e+00,1.052499e+00,1.500000e-01,1.500000e-01,1.500000e-01,2.100000e-02,4.795051e+01,...,1.000000e-03,6.775292e-01,0.000000e+00,3.474751e-01,1.000000e-03,3.533500e-01,5.670000e-03,4.713970e+00,1.000000e-01,0.000000e+00
date,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,1.567296e+12,...,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12,1.567382e+12

The database

In [ ]:
data = pd.read_csv('Coinbase_BTCUSD_ob_10_2019_09_01.csv.gz', compression='gzip',error_bad_lines=False)

In [18]:
class RevTypeCompares(object):
     def __init__(self, value):
         self.value = value
     def __gt__(self, other):
         return self.value < other[0:len(self.value)]
     def __lt__(self, other):
         return self.value[0:len(self.value)] > other

def find_mid_price(i):
    idx = bisect.bisect_left(list(i['type'].values), RevTypeCompares('a'))
    low = i['price'].values[0]
    high = i['price'].values[idx]

    return (low + high )/2

In [ ]:
# Get list of prices
prices = []
for date, i in data.groupby("date"):
    mid_price =  find_mid_price(i)
    prices.append(round(mid_price,3))

In [39]:
# Set price change between two timestamps as the target variable
price_change = pd.Series(prices).pct_change()[1:]

price_change = price_change.append(pd.Series([0]),ignore_index=True)
price_change[:-1]

0      -0.000791
1       0.000607
2      -0.000003
3       0.000094
4       0.000021
          ...
2855   -0.000241
2856    0.000005
2857    0.000018
2858    0.000324
2859    0.000126
Length: 2860, dtype: float64

In [20]:
# Adding target to the other bins shifted backwards 1 step
newdf['price'] = price_change
newdf = newdf[:-1]
target = newdf['price']
newdf.drop('price',axis=1,inplace=True)
newdf

,date,0,1,2,3,4,5,6,7,8,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,1567296016662,0.150000,0.085643,0.060785,0.300000,0.001000,0.020,1.469388,0.000000,0.028868,...,0.001000,0.000000,0.000000,1.960000,0.014926,1.544140,0.302000,0.003000,0.010289,1.027417
1,1567296049570,0.000000,0.411790,0.031548,12.105388,0.000000,0.000,1.052499,0.150000,0.085643,...,0.000000,0.002000,2.058017,0.002000,1.002200,3.554217,0.034335,14.718723,0.000000,0.001000
2,1567296076678,1.052499,0.150000,0.085643,0.055000,0.005785,0.300,0.021000,0.000000,1.469388,...,14.718723,0.000000,0.001000,0.000000,0.000000,1.960000,0.014926,1.544140,0.302000,0.003000
3,1567296109569,1.052499,0.150000,0.085643,0.000000,0.060785,0.300,0.021000,0.000000,1.469388,...,14.718723,0.000000,0.001000,0.000000,0.000000,1.960000,0.014926,1.544140,0.302000,0.003000
4,1567296136677,1.052499,0.150000,0.085643,0.060785,0.300000,0.021,0.000000,1.469388,0.000000,...,0.000000,0.001000,0.000000,0.000000,1.960000,0.014926,1.544140,0.302000,0.003000,0.010289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,1567382221495,0.001000,0.100000,0.000000,0.005000,0.677529,0.600,0.123000,0.110000,0.140000,...,1.301000,0.046642,0.000000,0.172911,0.079560,0.631749,1.000000,0.050000,0.010840,0.001000
2856,1567382248045,0.353350,4.713970,0.011300,0.101000,0.000000,0.005,0.677529,0.600000,0.123000,...,0.014845,0.000000,0.303200,1.046642,0.000000,0.000000,0.172911,0.079560,0.631749,1.050000
2857,1567382281511,0.005670,4.725270,0.001000,0.100000,0.000000,0.005,0.677529,0.600000,0.123000,...,0.014845,0.000000,0.303200,1.046642,0.000000,0.000000,0.172911,0.711309,0.000000,1.050000
2858,1567382308031,4.713970,0.011300,0.001000,0.100000,0.000000,0.005,0.677529,0.600000,0.123000,...,0.014845,0.000000,1.303200,0.046642,0.000000,0.172911,0.028560,0.682749,1.000000,0.050000
2859,1567382341505,0.100000,0.000000,0.005000,0.677529,0.600000,0.123,0.110000,0.140000,67.760830,...,0.046642,0.000000,0.172911,0.079560,0.631749,1.000000,0.051000,0.009840,0.001000,0.002000

Since in the previous steps we noticed the timestamp difference is not consistent and since each timestep is a snapshot of the orderbook the case can be made that they can be investigated as discrete values rather than a continous time-series

In [41]:
# Setting the X and y variables for use in logistic regression
X = newdf
y = target
def Boolean(x):
    if x>0:
        x=True
        return x
    else:
        x=False
        return x
target = target.map(lambda x:int(x>0))
# 0: negative 1: Positive

Splitting the data into train and test

In [42]:
from sklearn.model_selection import train_test_split
X_train_raw, X_test, y_train_raw, y_test = train_test_split(X, target, test_size=0.2,shuffle=False)
X_train, X_val, y_train, y_val = train_test_split(X_train_raw, y_train_raw,test_size=0.2,shuffle=False)
print("The target variable:")
y_train

The target variable:

0       0
1       1
2       0
3       1
4       1
       ..
1825    0
1826    0
1827    0
1828    0
1829    1
Length: 1830, dtype: int64

**Logistic Regression baseline:**

In [52]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9, solver='lbfgs')
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_val)

df = pd.DataFrame({'validation': y_val, 'linear_predicted': y_pred})
print("The model has returned its predicted values of the validation sample")
df['linear_abs_difference'] = abs(df['validation'] - df['linear_predicted'])
df['linear_abs_difference']
print("The prdiction was wrong {} out of {} entries \nAn accuracy of {}%".format(df['linear_abs_difference'].sum(),df.shape[0],round((1-df['linear_abs_difference'].sum()/df.shape[0])*100,2)))

df

The model has returned its predicted values of the validation sample
The prdiction was wrong 211 out of 458 entries
An accuracy of 53.93%

      validation  linear_predicted  linear_abs_difference
1830           1                 0                      1
1831           1                 0                      1
1832           0                 0                      0
1833           1                 0                      1
1834           1                 0                      1
...          ...               ...                    ...
2283           0                 0                      0
2284           0                 0                      0
2285           1                 0                      1
2286           0                 0                      0
2287           0                 0                      0

[458 rows x 3 columns]

**Further modelling available in the files: DENSE.ipynb, and LSTM.ipynb**

# Evaluation

 -The logistic regression model was run without thresholding on a binary price change of either positive/negative. It was seen to be incapable of accurately predicting a one step forward price change as the accuracy of the model returned 0.54
    
-The Linear Dense neural network model that was run afterwards included three classfication outputs 0,1,2 : sell, hold, buy. The model **training showed a very high accuracy of 0.96** when run at 100 epochs which seemed to be overfitting the data, since the **validation accuracy was 0.7** . Possible solutions include lower epoch number for a less over-fit model.
    
 -Finally the last model attempted which is the model that was chosen to be the best performing was the LSTM neural network model that returned a **validation score of 0.805** which was higher than the **training score of 0.762**, the model was run using a lower epoch number to prevent over-fitting and was consequently run on the test values.
   
-The final testing of the model returned a **test score of 0.805** which is equal to that of the validation which is always a good sign to see.